const COLOR_ROLES = {
  background: { label: 'Page Background', cssVar: '--bg-color' },
  sidebar: { label: 'Left Sidebar', cssVar: '--sidebar-bg' },
  panel: { label: 'Side Panel', cssVar: '--panel-bg' },
  surface: { label: 'Cards & Inputs', cssVar: '--surface-bg' },
  optionBg: { label: 'Selected Option', cssVar: '--option-bg' },
  optionText: { label: 'Option Text', cssVar: '--option-text' },
  textPrimary: { label: 'Main Text', cssVar: '--text-primary' },
  textSecondary: { label: 'Muted Text', cssVar: '--text-secondary' },
  accentColor: { label: 'Accent', cssVar: '--accent-color' },
  accentSoft: { label: 'Soft Accent', cssVar: '--accent-light' },
  borderColor: { label: 'Borders', cssVar: '--border-color' },
  ink: { label: 'Ink / Headings', cssVar: '--ink' },
  forest: { label: 'Library Green', cssVar: '--forest' },
  rust: { label: 'Library Red', cssVar: '--rust' },
  brass: { label: 'Brass Labels', cssVar: '--brass' },
  highlight: { label: 'Highlight', cssVar: '--highlight' },
  buttonBg: { label: 'Button Background', cssVar: '--button-bg' },
  buttonText: { label: 'Button Text', cssVar: '--button-text' },
  danger: { label: 'Danger', cssVar: '--danger-color' },
  success: { label: 'Success', cssVar: '--success-color' },
  cardBg: { label: 'Library Card', cssVar: '--library-card-bg' },
  cardBorder: { label: 'Library Card Border', cssVar: '--library-card-border' },
  pageBg: { label: 'Book Page', cssVar: '--book-page-bg' },
  pageText: { label: 'Book Page Text', cssVar: '--book-page-text' },
  messageSelfBg: { label: 'My Message', cssVar: '--message-self-bg' },
  messageSelfText: { label: 'My Message Text', cssVar: '--message-self-text' },
  messageOtherBg: { label: 'Other Message', cssVar: '--message-other-bg' },
  messageOtherText: { label: 'Other Message Text', cssVar: '--message-other-text' },
  overlay: { label: 'Overlay', cssVar: '--overlay-color' },
  shadow: { label: 'Shadow', cssVar: '--shadow-color' },
  // WelcomeCard picker
  pickerBg: { label: 'Picker Modal Background', cssVar: '--picker-bg' },
  pickerBorder: { label: 'Picker Modal Border', cssVar: '--picker-border' },
  pickerItemBg: { label: 'Picker Grid Item', cssVar: '--picker-item-bg' },
  pickerUploadBg: { label: 'Picker Upload Button', cssVar: '--picker-upload-bg' },
  pickerDivider: { label: 'Picker Divider Line', cssVar: '--picker-divider' },
  pickerCloseBg: { label: 'Picker Close Button', cssVar: '--picker-close-bg' },
  // WelcomeCard book visual
  bookSpine: { label: 'Book Spine', cssVar: '--book-spine-bg' },
  bookTextLine: { label: 'Book Text Lines', cssVar: '--book-text-line' },
  bookShadow: { label: 'Book Page Shadow', cssVar: '--book-page-shadow' },
  bookChapterText: { label: 'Chapter Label', cssVar: '--book-chapter-text' },
  welcomeCardBg: { label: 'Welcome Card Background', cssVar: '--welcome-card-bg' },
};

export const THEME_PRESETS = {
  cream: {
    key: 'cream',
    name: 'Cream',
    description: 'Warm ivory with clear dark text',
    background: '#F5F4EE',
    sidebar: '#F5F4EE',
    panel: '#FCFAF2',
    surface: '#F5F4EE',
    optionBg: '#F7F3E9',
    optionText: '#3E3B37',
    textPrimary: '#1E2022',
    textSecondary: '#5F6267',
    accentColor: '#B33933',
    accentSoft: '#FCE8E5',
    borderColor: '#DCD8CC',
    ink: '#1E2022',
    forest: '#2E3A2E',
    rust: '#B33933',
    brass: '#8A6A3A',
    highlight: '#FDF2F1',
    buttonBg: '#1E2022',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FCFAF2',
    cardBorder: '#D5CEBF',
    pageBg: '#FFFFFF',
    pageText: '#3E3B37',
    messageSelfBg: '#B33933',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FCFAF2',
    messageOtherText: '#2B2927',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FCFAF2',
    pickerBorder: '#D5CEBF',
    pickerItemBg: '#F5F2E8',
    pickerUploadBg: '#EDE8DB',
    pickerDivider: '#E4E0D6',
    pickerCloseBg: '#F0EDE4',
    bookSpine: '#2E3A2E',
    bookTextLine: '#DCD8CC',
    bookShadow: '#C8C4B4',
    bookChapterText: '#8A6A3A',
    welcomeCardBg: '#F5F4EE',
  },

  luxuryBurgundy: {
    key: 'luxuryBurgundy',
    name: 'Luxury Burgundy',
    description: 'Deep burgundy with elegant cream accents',
    background: '#5A162A',
    sidebar: '#5A162A',
    panel: '#6B2036',
    surface: '#5A162A',
    optionBg: '#743046',
    optionText: '#FFF8F3',
    textPrimary: '#FFF8F2',
    textSecondary: '#D8C4B9',
    accentColor: '#D66A82',
    accentSoft: '#F8E7EB',
    borderColor: '#7A3348',
    ink: '#FFF8F2',
    forest: '#E9D9D0',
    rust: '#D66A82',
    brass: '#E6C38A',
    highlight: '#7A3348',
    buttonBg: '#FFF8F2',
    buttonText: '#5A162A',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#6B2036',
    cardBorder: '#7A3348',
    pageBg: '#FFFDF9',
    pageText: '#352126',
    messageSelfBg: '#D66A82',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#6B2036',
    messageOtherText: '#FFF8F2',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#6B2036',
    pickerBorder: '#7A3348',
    pickerItemBg: '#743046',
    pickerUploadBg: '#7D3950',
    pickerDivider: '#8B4A5F',
    pickerCloseBg: '#743046',
    bookSpine: '#3A0A15',
    bookTextLine: '#D8C4B9',
    bookShadow: '#4A1021',
    bookChapterText: '#E6C38A',
    welcomeCardBg: '#6B2036',
  },

  roseGold: {
    key: 'roseGold',
    name: 'Rose Gold',
    description: 'Soft pink with grounded text',
    background: '#F9E5EB',
    sidebar: '#F9E5EB',
    panel: '#FFF2F5',
    surface: '#F9E5EB',
    optionBg: '#F5D8E2',
    optionText: '#44222D',
    textPrimary: '#2B1D22',
    textSecondary: '#6F5962',
    accentColor: '#C74B68',
    accentSoft: '#FCE8EE',
    borderColor: '#DFC6CF',
    ink: '#2B1D22',
    forest: '#5A2F39',
    rust: '#C74B68',
    brass: '#A56E42',
    highlight: '#FFF7F9',
    buttonBg: '#2B1D22',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FFF2F5',
    cardBorder: '#DFC6CF',
    pageBg: '#FFFFFF',
    pageText: '#44222D',
    messageSelfBg: '#C74B68',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FFF2F5',
    messageOtherText: '#2B1D22',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FFF2F5',
    pickerBorder: '#DFC6CF',
    pickerItemBg: '#F5D8E2',
    pickerUploadBg: '#FCE8EE',
    pickerDivider: '#E8D2D9',
    pickerCloseBg: '#F5D8E2',
    bookSpine: '#5A2F39',
    bookTextLine: '#DFC6CF',
    bookShadow: '#D9B8C2',
    bookChapterText: '#A56E42',
    welcomeCardBg: '#F9E5EB',
  },

  skyBlue: {
    key: 'skyBlue',
    name: 'Sky Blue',
    description: 'Airy blue with crisp panels',
    background: '#EDF5FE',
    sidebar: '#EDF5FE',
    panel: '#F8FBFF',
    surface: '#EDF5FE',
    optionBg: '#DCE9FA',
    optionText: '#24435D',
    textPrimary: '#1F2F3F',
    textSecondary: '#5C7082',
    accentColor: '#2F6DB2',
    accentSoft: '#E5F0FF',
    borderColor: '#D1DDEB',
    ink: '#1F2F3F',
    forest: '#24435D',
    rust: '#2F6DB2',
    brass: '#5E7CA0',
    highlight: '#F8FBFF',
    buttonBg: '#1F2F3F',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#F8FBFF',
    cardBorder: '#D1DDEB',
    pageBg: '#FFFFFF',
    pageText: '#24435D',
    messageSelfBg: '#2F6DB2',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#F8FBFF',
    messageOtherText: '#1F2F3F',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#F8FBFF',
    pickerBorder: '#D1DDEB',
    pickerItemBg: '#DCE9FA',
    pickerUploadBg: '#E5F0FF',
    pickerDivider: '#D8E4F2',
    pickerCloseBg: '#DCE9FA',
    bookSpine: '#24435D',
    bookTextLine: '#D1DDEB',
    bookShadow: '#C4D5E6',
    bookChapterText: '#5E7CA0',
    welcomeCardBg: '#EDF5FE',
  },

  seafoam: {
    key: 'seafoam',
    name: 'Seafoam',
    description: 'Cool mint and aqua with soft whites',
    background: '#DDF4EF',
    sidebar: '#DDF4EF',
    panel: '#F5FCFA',
    surface: '#DDF4EF',
    optionBg: '#CFECE6',
    optionText: '#29514D',
    textPrimary: '#1E3230',
    textSecondary: '#56716C',
    accentColor: '#2D8F83',
    accentSoft: '#E8F8F5',
    borderColor: '#C1DFD9',
    ink: '#1E3230',
    forest: '#29514D',
    rust: '#2D8F83',
    brass: '#6F9B7D',
    highlight: '#F8FEFD',
    buttonBg: '#1E3230',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#F5FCFA',
    cardBorder: '#C1DFD9',
    pageBg: '#FFFFFF',
    pageText: '#29514D',
    messageSelfBg: '#2D8F83',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#F5FCFA',
    messageOtherText: '#1E3230',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#F5FCFA',
    pickerBorder: '#C1DFD9',
    pickerItemBg: '#CFECE6',
    pickerUploadBg: '#E8F8F5',
    pickerDivider: '#D8ECE8',
    pickerCloseBg: '#CFECE6',
    bookSpine: '#29514D',
    bookTextLine: '#C1DFD9',
    bookShadow: '#B0D5CE',
    bookChapterText: '#6F9B7D',
    welcomeCardBg: '#DDF4EF',
  },

  goldAccent: {
    key: 'goldAccent',
    name: 'Gold Accent',
    description: 'Warm gold with readable contrast',
    background: '#F3E0C4',
    sidebar: '#F3E0C4',
    panel: '#FCF7F0',
    surface: '#F3E0C4',
    optionBg: '#F0D8B8',
    optionText: '#3D2D1D',
    textPrimary: '#1F1A17',
    textSecondary: '#645748',
    accentColor: '#A56B2C',
    accentSoft: '#F9EEDB',
    borderColor: '#D6BE97',
    ink: '#1F1A17',
    forest: '#5B4632',
    rust: '#A56B2C',
    brass: '#A56B2C',
    highlight: '#FEFBF6',
    buttonBg: '#1F1A17',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FCF7F0',
    cardBorder: '#D6BE97',
    pageBg: '#FFFFFF',
    pageText: '#3D2D1D',
    messageSelfBg: '#A56B2C',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FCF7F0',
    messageOtherText: '#1F1A17',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FCF7F0',
    pickerBorder: '#D6BE97',
    pickerItemBg: '#F0D8B8',
    pickerUploadBg: '#F9EEDB',
    pickerDivider: '#E5D0AA',
    pickerCloseBg: '#F0D8B8',
    bookSpine: '#5B4632',
    bookTextLine: '#D6BE97',
    bookShadow: '#C4AA82',
    bookChapterText: '#A56B2C',
    welcomeCardBg: '#F3E0C4',
  },
};

export const THEME_COLOR_ROLES = COLOR_ROLES;
export const THEME_LIST = Object.values(THEME_PRESETS);
export const DEFAULT_THEME_KEY = 'cream';

export function getSavedThemeOverrides() {
  try {
    return JSON.parse(localStorage.getItem('shelf_theme_overrides') || '{}');
  } catch {
    return {};
  }
}

export const applyTheme = (themeKey, textTone = 'standard', overrides = getSavedThemeOverrides()) => {
  const baseTheme = THEME_PRESETS[themeKey] || THEME_PRESETS[DEFAULT_THEME_KEY];
  const theme = { ...baseTheme, ...overrides };
  const root = document.documentElement;

  Object.entries(COLOR_ROLES).forEach(([key, role]) => {
    root.style.setProperty(role.cssVar, theme[key]);
  });

  let primaryText = theme.textPrimary;
  if (textTone === 'soft') primaryText = theme.textSecondary;
  if (textTone === 'strong') primaryText = theme.ink;

  root.style.setProperty('--text-primary', primaryText);
  root.style.setProperty('--forest-deep', theme.forest);
  root.style.setProperty('--serif', 'var(--font-serif)');
  root.style.setProperty('--sans', 'var(--font-sans)');
  root.style.setProperty('--ui-hover-bg', `color-mix(in srgb, ${theme.textPrimary} 8%, transparent)`);
  root.style.setProperty('--ui-active-shadow', `0 4px 12px color-mix(in srgb, ${theme.accentColor} 34%, transparent)`);
  root.style.setProperty('--shadow-sm', `0 2px 8px color-mix(in srgb, ${theme.shadow} 6%, transparent)`);
  root.style.setProperty('--shadow-md', `0 8px 24px color-mix(in srgb, ${theme.shadow} 8%, transparent)`);
  root.style.setProperty('--shadow-lg', `0 16px 40px color-mix(in srgb, ${theme.shadow} 12%, transparent)`);
  root.style.setProperty('--data-text-tone', textTone);

  return theme;
};