const COLOR_ROLES = {
  background: { label: 'Page Background', cssVar: '--bg-color' },
  sidebar: { label: 'Left Sidebar', cssVar: '--sidebar-bg' },
  panel: { label: 'Side Panel', cssVar: '--panel-bg' },
  surface: { label: 'Cards & Inputs', cssVar: '--surface-bg' },
  optionBg: { label: 'Selected Option', cssVar: '--option-bg' },
  optionText: { label: 'Option Text', cssVar: '--option-text' },
  textPrimary: { label: 'Main Text', cssVar: '--text-primary' },
  textSecondary: { label: 'Muted Text', cssVar: '--text-secondary' },
  accentColor: { label: 'Accent', cssVar: '--accent-color' },
  accentSoft: { label: 'Soft Accent', cssVar: '--accent-light' },
  borderColor: { label: 'Borders', cssVar: '--border-color' },
  ink: { label: 'Ink / Headings', cssVar: '--ink' },
  forest: { label: 'Library Green', cssVar: '--forest' },
  rust: { label: 'Library Red', cssVar: '--rust' },
  brass: { label: 'Brass Labels', cssVar: '--brass' },
  highlight: { label: 'Highlight', cssVar: '--highlight' },
  buttonBg: { label: 'Button Background', cssVar: '--button-bg' },
  buttonText: { label: 'Button Text', cssVar: '--button-text' },
  danger: { label: 'Danger', cssVar: '--danger-color' },
  success: { label: 'Success', cssVar: '--success-color' },
  cardBg: { label: 'Library Card', cssVar: '--library-card-bg' },
  cardBorder: { label: 'Library Card Border', cssVar: '--library-card-border' },
  pageBg: { label: 'Book Page', cssVar: '--book-page-bg' },
  pageText: { label: 'Book Page Text', cssVar: '--book-page-text' },
  messageSelfBg: { label: 'My Message', cssVar: '--message-self-bg' },
  messageSelfText: { label: 'My Message Text', cssVar: '--message-self-text' },
  messageOtherBg: { label: 'Other Message', cssVar: '--message-other-bg' },
  messageOtherText: { label: 'Other Message Text', cssVar: '--message-other-text' },
  overlay: { label: 'Overlay', cssVar: '--overlay-color' },
  shadow: { label: 'Shadow', cssVar: '--shadow-color' },
  // WelcomeCard picker
  pickerBg: { label: 'Picker Modal Background', cssVar: '--picker-bg' },
  pickerBorder: { label: 'Picker Modal Border', cssVar: '--picker-border' },
  pickerItemBg: { label: 'Picker Grid Item', cssVar: '--picker-item-bg' },
  pickerUploadBg: { label: 'Picker Upload Button', cssVar: '--picker-upload-bg' },
  pickerDivider: { label: 'Picker Divider Line', cssVar: '--picker-divider' },
  pickerCloseBg: { label: 'Picker Close Button', cssVar: '--picker-close-bg' },
  // WelcomeCard book visual
  bookSpine: { label: 'Book Spine', cssVar: '--book-spine-bg' },
  bookTextLine: { label: 'Book Text Lines', cssVar: '--book-text-line' },
  bookShadow: { label: 'Book Page Shadow', cssVar: '--book-page-shadow' },
  bookChapterText: { label: 'Chapter Label', cssVar: '--book-chapter-text' },
  welcomeCardBg: { label: 'Welcome Card Background', cssVar: '--welcome-card-bg' },
};

export const THEME_PRESETS = {
  cream: {
    key: 'cream',
    name: 'Cream',
    description: 'Warm ivory with clear dark text',
    background: '#F5F4EE',
    sidebar: '#F5F4EE',
    panel: '#FCFAF2',
    surface: '#F5F4EE',
    optionBg: '#F7F3E9',
    optionText: '#3E3B37',
    textPrimary: '#1E2022',
    textSecondary: '#5F6267',
    accentColor: '#B33933',
    accentSoft: '#FCE8E5',
    borderColor: '#DCD8CC',
    ink: '#1E2022',
    forest: '#2E3A2E',
    rust: '#B33933',
    brass: '#8A6A3A',
    highlight: '#FDF2F1',
    buttonBg: '#1E2022',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FCFAF2',
    cardBorder: '#D5CEBF',
    pageBg: '#FFFFFF',
    pageText: '#3E3B37',
    messageSelfBg: '#B33933',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FCFAF2',
    messageOtherText: '#2B2927',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FCFAF2',
    pickerBorder: '#D5CEBF',
    pickerItemBg: '#F5F2E8',
    pickerUploadBg: '#EDE8DB',
    pickerDivider: '#E4E0D6',
    pickerCloseBg: '#F0EDE4',
    bookSpine: '#2E3A2E',
    bookTextLine: '#DCD8CC',
    bookShadow: '#C8C4B4',
    bookChapterText: '#8A6A3A',
    welcomeCardBg: '#F5F4EE',
  },
  roseGold: {
    key: 'roseGold',
    name: 'Rose Gold',
    description: 'Soft pink with grounded text',
    background: '#F9E5EB',
    sidebar: '#F9E5EB',
    panel: '#FFF2F5',
    surface: '#F9E5EB',
    optionBg: '#F5D8E2',
    optionText: '#44222D',
    textPrimary: '#2B1D22',
    textSecondary: '#6F5962',
    accentColor: '#C74B68',
    accentSoft: '#FCE8EE',
    borderColor: '#DFC6CF',
    ink: '#2B1D22',
    forest: '#5A2F39',
    rust: '#C74B68',
    brass: '#A56E42',
    highlight: '#FFF7F9',
    buttonBg: '#2B1D22',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FFF2F5',
    cardBorder: '#DFC6CF',
    pageBg: '#FFFFFF',
    pageText: '#44222D',
    messageSelfBg: '#C74B68',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FFF2F5',
    messageOtherText: '#2B1D22',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FFF2F5',
    pickerBorder: '#DFC6CF',
    pickerItemBg: '#F5D8E2',
    pickerUploadBg: '#FCE8EE',
    pickerDivider: '#E8D2D9',
    pickerCloseBg: '#F5D8E2',
    bookSpine: '#5A2F39',
    bookTextLine: '#DFC6CF',
    bookShadow: '#D9B8C2',
    bookChapterText: '#A56E42',
    welcomeCardBg: '#F9E5EB',
  },

  skyBlue: {
    key: 'skyBlue',
    name: 'Sky Blue',
    description: 'Airy blue with crisp panels',
    background: '#EDF5FE',
    sidebar: '#EDF5FE',
    panel: '#F8FBFF',
    surface: '#EDF5FE',
    optionBg: '#DCE9FA',
    optionText: '#24435D',
    textPrimary: '#1F2F3F',
    textSecondary: '#5C7082',
    accentColor: '#2F6DB2',
    accentSoft: '#E5F0FF',
    borderColor: '#D1DDEB',
    ink: '#1F2F3F',
    forest: '#24435D',
    rust: '#2F6DB2',
    brass: '#5E7CA0',
    highlight: '#F8FBFF',
    buttonBg: '#1F2F3F',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#F8FBFF',
    cardBorder: '#D1DDEB',
    pageBg: '#FFFFFF',
    pageText: '#24435D',
    messageSelfBg: '#2F6DB2',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#F8FBFF',
    messageOtherText: '#1F2F3F',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#F8FBFF',
    pickerBorder: '#D1DDEB',
    pickerItemBg: '#DCE9FA',
    pickerUploadBg: '#E5F0FF',
    pickerDivider: '#D8E4F2',
    pickerCloseBg: '#DCE9FA',
    bookSpine: '#24435D',
    bookTextLine: '#D1DDEB',
    bookShadow: '#C4D5E6',
    bookChapterText: '#5E7CA0',
    welcomeCardBg: '#EDF5FE',
  },

  seafoam: {
    key: 'seafoam',
    name: 'Seafoam',
    description: 'Cool mint and aqua with soft whites',
    background: '#DDF4EF',
    sidebar: '#DDF4EF',
    panel: '#F5FCFA',
    surface: '#DDF4EF',
    optionBg: '#CFECE6',
    optionText: '#29514D',
    textPrimary: '#1E3230',
    textSecondary: '#56716C',
    accentColor: '#2D8F83',
    accentSoft: '#E8F8F5',
    borderColor: '#C1DFD9',
    ink: '#1E3230',
    forest: '#29514D',
    rust: '#2D8F83',
    brass: '#6F9B7D',
    highlight: '#F8FEFD',
    buttonBg: '#1E3230',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#F5FCFA',
    cardBorder: '#C1DFD9',
    pageBg: '#FFFFFF',
    pageText: '#29514D',
    messageSelfBg: '#2D8F83',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#F5FCFA',
    messageOtherText: '#1E3230',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#F5FCFA',
    pickerBorder: '#C1DFD9',
    pickerItemBg: '#CFECE6',
    pickerUploadBg: '#E8F8F5',
    pickerDivider: '#D8ECE8',
    pickerCloseBg: '#CFECE6',
    bookSpine: '#29514D',
    bookTextLine: '#C1DFD9',
    bookShadow: '#B0D5CE',
    bookChapterText: '#6F9B7D',
    welcomeCardBg: '#DDF4EF',
  },

  lightLuxurySage: {
    key: 'lightLuxurySage',
    name: 'Luxury Sage',
    description: 'Soft sage with ivory and gold accents',
    background: '#F5F7F2',
    sidebar: '#F5F7F2',
    panel: '#FAFBF7',
    surface: '#F5F7F2',
    optionBg: '#EEF3EA',
    optionText: '#3B3F3C',
    textPrimary: '#1D221F',
    textSecondary: '#5C635F',
    accentColor: '#5F8A68',
    accentSoft: '#EAF4EC',
    borderColor: '#D6DDD5',
    ink: '#1D221F',
    forest: '#2B3A30',
    rust: '#5F8A68',
    brass: '#8A7A4A',
    highlight: '#F2F8F3',
    buttonBg: '#1D221F',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FAFBF7',
    cardBorder: '#D2DBD3',
    pageBg: '#FFFFFF',
    pageText: '#3B3F3C',
    messageSelfBg: '#5F8A68',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FAFBF7',
    messageOtherText: '#2B2F2C',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FAFBF7',
    pickerBorder: '#D2DBD3',
    pickerItemBg: '#EEF3EA',
    pickerUploadBg: '#EAF4EC',
    pickerDivider: '#E1E8E2',
    pickerCloseBg: '#EEF3EA',
    bookSpine: '#2B3A30',
    bookTextLine: '#D6DDD5',
    bookShadow: '#C8D1C9',
    bookChapterText: '#8A7A4A',
    welcomeCardBg: '#F5F7F2',
  },

  lightChampagne: {
    key: 'lightChampagne',
    name: 'Champagne',
    description: 'Elegant champagne with warm gold accents',
    background: '#FBF8F2',
    sidebar: '#F7F1E7',
    panel: '#FCFAF5',
    surface: '#F7F1E7',
    optionBg: '#F2E8D8',
    optionText: '#4A3A2A',
    textPrimary: '#1F1A16',
    textSecondary: '#6F5F4E',
    accentColor: '#C79B4B',
    accentSoft: '#FBF3E2',
    borderColor: '#E6D8C3',
    ink: '#1F1A16',
    forest: '#4A3A2A',
    rust: '#C79B4B',
    brass: '#9E7B3E',
    highlight: '#FFF8EC',
    buttonBg: '#1F1A16',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FCFAF5',
    cardBorder: '#E6D8C3',
    pageBg: '#FFFFFF',
    pageText: '#4A3A2A',
    messageSelfBg: '#C79B4B',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#FCF6ED',
    messageOtherText: '#1F1A16',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FCFAF5',
    pickerBorder: '#E6D8C3',
    pickerItemBg: '#F2E8D8',
    pickerUploadBg: '#FBF3E2',
    pickerDivider: '#E9DDC9',
    pickerCloseBg: '#F2E8D8',
    bookSpine: '#4A3A2A',
    bookTextLine: '#E6D8C3',
    bookShadow: '#D6C5AA',
    bookChapterText: '#9E7B3E',
    welcomeCardBg: '#FBF8F2',
  },

  lightLavender: {
    key: 'lightLavender',
    name: 'Luxury Lavender',
    description: 'Soft lavender with elegant plum accents',
    background: '#F8F6FC',
    sidebar: '#F1EDF8',
    panel: '#FBFAFE',
    surface: '#F1EDF8',
    optionBg: '#E9E3F5',
    optionText: '#3F2F55',
    textPrimary: '#1C1528',
    textSecondary: '#6A5A85',
    accentColor: '#7A5CCF',
    accentSoft: '#F0EBFC',
    borderColor: '#DCD3F0',
    ink: '#1C1528',
    forest: '#3F2F55',
    rust: '#7A5CCF',
    brass: '#9C83D6',
    highlight: '#F7F5FF',
    buttonBg: '#1C1528',
    buttonText: '#FFFFFF',
    danger: '#D94A43',
    success: '#2F7A4F',
    cardBg: '#FBFAFE',
    cardBorder: '#DCD3F0',
    pageBg: '#FFFFFF',
    pageText: '#3F2F55',
    messageSelfBg: '#7A5CCF',
    messageSelfText: '#FFFFFF',
    messageOtherBg: '#F4F1FB',
    messageOtherText: '#1C1528',
    overlay: '#000000',
    shadow: '#000000',
    pickerBg: '#FBFAFE',
    pickerBorder: '#DCD3F0',
    pickerItemBg: '#E9E3F5',
    pickerUploadBg: '#F0EBFC',
    pickerDivider: '#E6DDF7',
    pickerCloseBg: '#E9E3F5',
    bookSpine: '#3F2F55',
    bookTextLine: '#DCD3F0',
    bookShadow: '#D1C4EC',
    bookChapterText: '#9C83D6',
    welcomeCardBg: '#F8F6FC',
  },
};

export const THEME_COLOR_ROLES = COLOR_ROLES;
export const THEME_LIST = Object.values(THEME_PRESETS);
export const DEFAULT_THEME_KEY = 'cream';

export function getSavedThemeOverrides() {
  try {
    return JSON.parse(localStorage.getItem('shelf_theme_overrides') || '{}');
  } catch {
    return {};
  }
}

export const applyTheme = (themeKey, textTone = 'standard', overrides = getSavedThemeOverrides()) => {
  const baseTheme = THEME_PRESETS[themeKey] || THEME_PRESETS[DEFAULT_THEME_KEY];
  const theme = { ...baseTheme, ...overrides };
  const root = document.documentElement;

  Object.entries(COLOR_ROLES).forEach(([key, role]) => {
    root.style.setProperty(role.cssVar, theme[key]);
  });

  let primaryText = theme.textPrimary;
  if (textTone === 'soft') primaryText = theme.textSecondary;
  if (textTone === 'strong') primaryText = theme.ink;

  root.style.setProperty('--text-primary', primaryText);
  root.style.setProperty('--forest-deep', theme.forest);
  root.style.setProperty('--serif', 'var(--font-serif)');
  root.style.setProperty('--sans', 'var(--font-sans)');
  root.style.setProperty('--ui-hover-bg', `color-mix(in srgb, ${theme.textPrimary} 8%, transparent)`);
  root.style.setProperty('--ui-active-shadow', `0 4px 12px color-mix(in srgb, ${theme.accentColor} 34%, transparent)`);
  root.style.setProperty('--shadow-sm', `0 2px 8px color-mix(in srgb, ${theme.shadow} 6%, transparent)`);
  root.style.setProperty('--shadow-md', `0 8px 24px color-mix(in srgb, ${theme.shadow} 8%, transparent)`);
  root.style.setProperty('--shadow-lg', `0 16px 40px color-mix(in srgb, ${theme.shadow} 12%, transparent)`);
  root.style.setProperty('--data-text-tone', textTone);

  return theme;
};